# Generated by Django 3.2.2 on 2021-06-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=2000)),
                ('link', models.CharField(max_length=2000)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
