# Generated by Django 3.2.2 on 2021-06-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210601_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.FilePathField(path='static/img/'),
        ),
    ]
