# Generated by Django 3.2.2 on 2021-06-02 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='linkavia',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='linkbus',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
